[package]
name = "album_maker"
version = "0.1.0"
authors = ["jamie <jamieapps101@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
image = "0.23.14"
regex = "1.5.4"
rayon = "1.5.1"